apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: ts-mern-thaitogo-backend:latest  # Replace with your actual Docker image name and tag
          ports:
            - containerPort: 4000  # Port your backend application listens on
          readinessProbe:
            httpGet:
              path: /health  # Endpoint to check the health of your backend
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health  # Endpoint to check if your backend is alive
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 15
