import bcrypt from 'bcryptjs'
import { User } from './models/userModel'
import { Product } from './models/productModel'

export const sampleProducts: Product[] = [
  {
    name: 'Tao Hu Tod',
    slug: 'tao-hu-tod',
    category: 'Appetizers',
    image: '../images/taohutod.jpg',
    price: 8.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.8,
    numReviews: 209,
    description: 'Deep fried tofu served with sweet peanut sauce',
  },
  {
    name: 'Mee Grop',
    slug: 'mee-grop',
    category: 'Appetizers',
    image: '../images/meegrop.jpg',
    price: 9.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.0,
    numReviews: 9,
    description:
      'Crisp vermicelli with sweet and sour caramelize tamarind sauce, crisp tofu, chives and bean sprouts',
  },
  {
    name: 'Vegetarian Spring Rolls',
    slug: 'vegetarian-spring-rolls',
    category: 'Appetizers',
    image: '../images/vegetarianspringrolls.jpg',
    price: 8.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.5,
    numReviews: 56,
    description:
      'Deep fried spring rolls filled with cabbages, carrots and glass noodles served with plum sauce',
  },
  {
    name: 'Crisy Wonton',
    slug: 'crispy-wonton',
    category: 'Appetizers',
    image: '../images/crispywonton.jpg',
    price: 8.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.8,
    numReviews: 78,
    description:
      'Deep fried wonton stuffed with marinated ground chicken and served with plum sauce',
  },
  {
    name: 'Fish Cake',
    slug: 'fish-cake',
    category: 'Appetizers',
    image: '../images/fishcake.jpg',
    price: 12.99,
    countInStock: 87,
    brand: 'Chad Thai',
    rating: 4.3,
    numReviews: 102,
    description:
      'Deep fried fish cakes, ground fish blended with chili paste, green beans, kaffir lime leaves, and served with spicy sweet and sour sauce',
  },
  {
    name: 'Chicken Wings',
    slug: 'chicken-wings',
    category: 'Appetizers',
    image: '../images/chickenwings.jpg',
    price: 10.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.5,
    numReviews: 145,
    description: 'Crispy fried chicken wings marinated in spices and garlic',
  },
  {
    name: 'Chad Thai Garden',
    slug: 'chad-thai-garden',
    category: 'Appetizers',
    image: '../images/chadthaigarden.jpg',
    price: 10.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.0,
    numReviews: 99,
    description:
      'Fresh roll wrapper stuffed with tofu, mushroom, carrot, lettuce and basil, and served with spicy sauce',
  },
  {
    name: 'Chicken Satay',
    slug: 'chicken-satay',
    category: 'Grill',
    image: '../images/chickensatay.jpg',
    price: 11.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.2,
    numReviews: 100,
    description:
      'Skewered and grilled chicken marinated in coconut milk, turmeric, garlic, Thai spices, and served with peanut sauce and salsa of pickled cucumber and red onions',
  },
  {
    name: 'Mu Yang',
    slug: 'mu-yang',
    category: 'Grill',
    image: '../images/muyang.jpg',
    price: 12.99,
    countInStock: 111,
    brand: 'Chad Thai',
    rating: 4.5,
    numReviews: 98,
    description:
      'Thai grilled pork marinated in Thai herbs and spices, and served with sweet chili sauce or spicy Thai dip',
  },
  {
    name: 'Gai Yang',
    slug: 'gai-yang',
    category: 'Grill',
    image: '../images/gaiyang.jpg',
    price: 12.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.6,
    numReviews: 93,
    description:
      'Thai grilled chicken marinated in Thai herbs and spices, and served with sweet chili sauce or spicy Thai dip',
  },
  {
    name: 'Pla Muek Yang',
    slug: 'pla-muek-yang',
    category: 'Grill',
    image: '../images/plamuekyang.jpg',
    price: 13.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.8,
    numReviews: 130,
    description:
      'Thai grilled squid marinated in Thai herbs and spices, and served with sweet chili sauce or spicy Thai dip',
  },
  {
    name: 'Tom Yum Goong',
    slug: 'tom-yum-goong',
    category: 'Soup',
    image: '../images/tomyumgoong.jpg',
    price: 14.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.9,
    numReviews: 150,
    description:
      'A spicy and sour creamy soup with white mushrooms, coriander, lemongrass, red onions, kaffir lime leaves, and galangal',
  },
  {
    name: 'Tom Yum Talay',
    slug: 'tom-yum-talay',
    category: 'Soup',
    image: '../images/tomyumtalay.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.7,
    numReviews: 122,
    description:
      'A spicy and sour creamy soup with white mushrooms, coriander, lemongrass, red onions, kaffir lime leaves, and galangal',
  },
  {
    name: 'Poh Tag',
    slug: 'poh-tag',
    category: 'Soup',
    image: '../images/pohtag.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.4,
    numReviews: 88,
    description:
      'Hot and sour mixed seafood soup with white mushrooms, basils, coriander, lemongrass, red onions, kaffir lime leaves, and galangal',
  },
  {
    name: 'Tom Kha Gai',
    slug: 'tom-kha-gai',
    category: 'Soup',
    image: '../images/tomkhagai.jpg',
    price: 13.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.2,
    numReviews: 94,
    description:
      'A spicy light coconut chicken soup with white mushrooms, coriander, lemongrass, onions, kaffir lime leaves, and galangal',
  },
  {
    name: 'Wonton Soup',
    slug: 'wonton-soup',
    category: 'Soup',
    image: '../images/wontonsoup.jpg',
    price: 13.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.5,
    numReviews: 198,
    description:
      'Ground marinated chicken wrapped with wonton in stock, bean sprouts, shredded coriander, and green onion',
  },
  {
    name: 'Green Curry',
    slug: 'green-curry',
    category: 'Curry',
    image: '../images/greencurry.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.9,
    numReviews: 222,
    description:
      'Choice of chicken/beef/pork, made with a spicy green curry paste, then cooked in coconut milk with eggplants, peppers, green beans, and kaffir lime leaves then finished with Thai basil',
  },
  {
    name: 'Red Curry',
    slug: 'red-curry',
    category: 'Curry',
    image: '../images/redcurry.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.6,
    numReviews: 198,
    description:
      'Choice of chicken/beef/pork, made with a spicy red curry paste, then cooked in coconut milk with eggplants, bamboo shoots, peppers, and kaffir lime leaves then finished with Thai basil',
  },
  {
    name: 'Panang Curry',
    slug: 'panang-curry',
    category: 'Curry',
    image: '../images/panangcurry.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.5,
    numReviews: 190,
    description:
      'Choice of chicken/beef/pork, peppers, kaffir lime leaves, Thai basil, ground peanut in panang curry with coconut milk',
  },
  {
    name: 'Mussamun Curry',
    slug: 'mussamun-curry',
    category: 'Curry',
    image: '../images/mussamuncurry.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.3,
    numReviews: 190,
    description:
      'Choice of chicken/beef/pork, made with a milk mussamun curry paste, the aromatic paste is cooked in coconut milk, tamarind juice, pineapple, potatoes, and peanuts',
  },
  {
    name: 'Yellow Curry',
    slug: 'yellow-curry',
    category: 'Curry',
    image: '../images/yellowcurry.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.7,
    numReviews: 134,
    description:
      'Choice of chicken/beef/pork, made with a yellow curry paste, the aromatic paste is cooked in coconut milk, potatoes, and onions',
  },
  {
    name: 'Pad Gra Pao',
    slug: 'pad-gra-pao',
    category: 'Thai Wok Fried',
    image: '../images/padgrapao.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.9,
    numReviews: 304,
    description:
      'Stir fried ground chicken/pork with green beans, garlic, fresh chili, and Thai holy basil',
  },
  {
    name: 'Pad Ped',
    slug: 'pad-ped',
    category: 'Thai Wok Fried',
    image: '../images/padped.jpg',
    price: 15.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.3,
    numReviews: 200,
    description:
      'Stir fried chicken/beef/pork with red curry paste, green beans, bell peppers, and kaffir lime',
  },
  {
    name: 'Pad Nam Prig Pao',
    slug: 'pad-nam-prig-pao',
    category: 'Thai Wok Fried',
    image: '../images/padnamprigpao.jpg',
    price: 15.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.5,
    numReviews: 183,
    description:
      'Stir fried chicken/beef/pork with chili jam, onions, and bell peppers',
  },
  {
    name: 'Chicken Cashew',
    slug: 'chicken-cashew',
    category: 'Thai Wok Fried',
    image: '../images/chickencashew.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.1,
    numReviews: 156,
    description:
      'Stir fried chicken with cashew nuts, bell peppers, and onions',
  },
  {
    name: 'Pad Khing',
    slug: 'pad-khing',
    category: 'Thai Wok Fried',
    image: '../images/padkhing.jpg',
    price: 15.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.4,
    numReviews: 304,
    description:
      'Stir fried chicken/beef/pork with ginger, white mushrooms, onions, and green onions',
  },
  {
    name: 'Sweet and Sour',
    slug: 'sweet-and-sour',
    category: 'Thai Wok Fried',
    image: '../images/sweetandsour.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.4,
    numReviews: 344,
    description:
      'Stir fried ground chicken/beef/pork with bell peppers, onions, cucumbers, tomatoes and then finished with green onions',
  },
  {
    name: 'Pad Eggplant',
    slug: 'pad-eggplant',
    category: 'Thai Wok Fried',
    image: '../images/padeggplant.jpg',
    price: 15.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.9,
    numReviews: 444,
    description:
      'Stir fried eggplant, peppers, onions, Thai basil with chili jam',
  },
  {
    name: 'Drunken Seafood',
    slug: 'drunken-seafood',
    category: 'Seafood',
    image: '../images/drunkenseafood.jpg',
    price: 19.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.8,
    numReviews: 420,
    description:
      'Stir friend mixed seafood, fresh chili sauce, onions, bell peppers, kaffir lime leaves, and Thai basil',
  },
  {
    name: 'Seafood Pad Prig Pao',
    slug: 'seafood-pad-prig-pao',
    category: 'Seafood',
    image: '../images/seafoodpadprigpao.jpg',
    price: 19.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.6,
    numReviews: 399,
    description:
      'Stir fried mixed seafood with Thai chili jam, bell peppers, and onions',
  },
  {
    name: 'Seafood Pad Pong Karee',
    slug: 'seafood-pad-pong-karee',
    category: 'Seafood',
    image: '../images/seafoodpadpongkaree.jpg',
    price: 19.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.5,
    numReviews: 288,
    description:
      'Stir fried mixed seafood with curry powder, eggs, onions, celery, and green onions',
  },
  {
    name: 'Fried Rice',
    slug: 'fried-rice',
    category: 'Rice',
    image: '../images/friedrice.jpg',
    price: 15.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.7,
    numReviews: 387,
    description:
      'Stir fried chicken/beef/pork with rice, egg, finely diced carrots, and green onions',
  },
  {
    name: 'Krapao Fried Rice',
    slug: 'krapao-fried-rice',
    category: 'Rice',
    image: '../images/krapaofriedrice.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.6,
    numReviews: 380,
    description:
      'Stir fried chicken/beef/pork with rice, green beans, fresh chili, and Thai holy basil',
  },
  {
    name: 'Green Curry Fried Rice',
    slug: 'green-curry-fried-rice',
    category: 'Rice',
    image: '../images/greencurryfriedrice.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.7,
    numReviews: 509,
    description:
      'Stir fried chicken/beef/pork with rice, green curry paste, green beans, peppers, and Thai basil',
  },
  {
    name: 'Pad Thai',
    slug: 'pad-thai',
    category: 'Thai Noodle',
    image: '../images/padthai.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.9,
    numReviews: 834,
    description:
      'Stir fried thin rice noodles in tamarind sauce, tofu, salted radish, egg, chives, bean sprouts, and ground peanuts',
  },
  {
    name: 'Pad Siew',
    slug: 'pad-siew',
    category: 'Thai Noodle',
    image: '../images/padsiew.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.9,
    numReviews: 656,
    description:
      'Stir fried chicken/beef/pork with thick rice noodles, gailan, carrots, and egg in dark soy sauce seasoning',
  },
  {
    name: 'Pad Ki Mao',
    slug: 'pad-ki-mao',
    category: 'Thai Noodle',
    image: '../images/padkimao.jpg',
    price: 15.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.9,
    numReviews: 459,
    description:
      'Stir fried chicken/beef/pork with thin rice noodles, onions, bell peppers, fresh chili, kaffir lime leaves, and Thai basil',
  },
  {
    name: 'Lad Na',
    slug: 'lad-na',
    category: 'Thai Noodle',
    image: '../images/ladna.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.9,
    numReviews: 208,
    description:
      'Choice of crispy egg noodles or thick rice noodles topped with chicken/beef/pork, gailan, and carrots in Thai style gravy',
  },
  {
    name: 'Khao Soi Gai',
    slug: 'khao-soi-gai',
    category: 'Thai Noodle',
    image: '../images/khaosoigai.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4.8,
    numReviews: 354,
    description:
      'Egg noodles and sliced chicken breast in curry sauce then topped with coriander and green onion and served with red onions, pickle cabbage, lime, and chili oil',
  },
  {
    name: 'Tom Yum Noodle',
    slug: 'tom-yum',
    category: 'Thai Noodle',
    image: '../images/tomyum.jpg',
    price: 16.99,
    countInStock: 50,
    brand: 'Chad Thai',
    rating: 4,
    numReviews: 12,
    description:
      'Egg noodles and sliced chicken breast in curry sauce then topped with coriander and green onion and served with red onions, pickle cabbage, lime, and chili oil',
  },
  {
    name: 'Thai Iced Tea',
    slug: 'thai-iced-tea',
    category: 'Beverages',
    image: '../images/thaiicedtea.jpg',
    price: 4.0,
    countInStock: 100,
    brand: 'Chad Thai',
    rating: 4.9,
    numReviews: 655,
    description: 'Traditional Thai Iced Thai',
  },
]

export const sampleUsers: User[] = [
  {
    name: 'Mary',
    email: 'chadthai@gmail.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: true,
  },
  {
    name: 'John',
    email: 'john@hotmail.com',
    password: bcrypt.hashSync('abcde'),
    isAdmin: false,
  },
]
